# Generated by Django 3.2 on 2024-10-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Damkaapp', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
