# Generated by Django 3.2 on 2024-10-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Damkaapp', '0004_auto_20241027_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='admin_profile',
        ),
    ]
